
name: build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 2
        
    - run: git checkout HEAD^

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
