name: pre-release

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Prepare Release
        run: ./mvnw -B clean package

      - name: Increment Version
        run: ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit

      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.BUILD_EMAIL }}
          git config --local user.name ${{ secrets.BUILD_USERNAME }}
          [[ `git diff` ]] && git commit -m "Update version in pom.xml" -a || echo "ignore commit, no changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}