name: Pre-Release

on:
  pull_request:
    branches: master

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out pull request head
      uses: actions/checkout@v2.3.1
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: mvn -B test --file pom.xml

  increment-version:
    name: Increment POM version
    runs-on: ubuntu-latest

    steps:
    - name: Check out pull request head
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Get latest release version
      run: |
        curl -X GET \
          https://api.github.com/repos/whelk-io/hy-phen-a-tion/releases/latest \
          -o /tmp/release.json

    - name: Increment version in pom.xml
      run: |
        old_version=`cat /tmp/release.json | grep tag_name -m 1 | awk '{$1=$1};1' | awk -F':' '{print $2}' | awk -F'"' '{print $2}'` \
        && echo "Old version: " $old_version \
        && major_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $1}'` \
        && minor_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $2}'` \
        && patch_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $3}'` \
        && let "patch_version+=1" \
        && new_version=$major_version"."$minor_version"."$patch_version"-RELEASE" \
        && echo "New version: " $new_version \
        && mvn -B versions:set -DnewVersion=$new_version --file pom.xml

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Increment version in pom.xml

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
